---
version: '3.9'

services:
  console-api:
    image: ${CONSOLE_API_IMAGE}
    volumes:
      - ${PWD}/console-config.yaml:/deployments/console-config.yaml:z
    ports:
      - :8080
    environment:
      CONSOLE_CONFIG_PATH: /deployments/console-config.yaml
      QUARKUS_KUBERNETES_CLIENT_API_SERVER_URL: ${CONSOLE_API_KUBERNETES_API_SERVER_URL}
      QUARKUS_KUBERNETES_CLIENT_TRUST_CERTS: "true"
      QUARKUS_KUBERNETES_CLIENT_TOKEN: ${CONSOLE_API_SERVICE_ACCOUNT_TOKEN}
    labels:
      io.streamshub.console.container: api

  console-ui:
    image: ${CONSOLE_UI_IMAGE}
    ports:
      - :3000
    environment:
      NEXTAUTH_SECRET: ${CONSOLE_UI_NEXTAUTH_SECRET}
      NEXTAUTH_URL: http://localhost:3000
      BACKEND_URL: http://console-api:8080/
    labels:
      io.streamshub.console.container: ui
