name: Main changed - build, then release and update GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.19.0

  update-storybook-on-ghpages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3.0.2

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Set up environment variables
        run: |
          echo "NEXTAUTH_SECRET=" >> $GITHUB_ENV
          echo "NEXTAUTH_URL=$(grep NEXTAUTH_URL .env.example | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "KEYCLOAK_CLIENT_ID=$(grep KEYCLOAK_CLIENT_ID .env.example | cut -d '=' -f2)" >> $GITHUB_ENV
          echo "KEYCLOAK_CLIENT_SECRET=$(grep KEYCLOAK_CLIENT_SECRET .env.example | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Show environment variables
        run: |
          echo "NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
          echo "NEXTAUTH_URL: $NEXTAUTH_URL"
          echo "KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID"
          echo "KEYCLOAK_CLIENT_SECRET: $KEYCLOAK_CLIENT_SECRET"

      - name: Build storybook
        run: |
          npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: src/storybook-static # The folder the action should deploy.
