name: Main changed - build, then release and update GH Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.19.0

  update-storybook-on-ghpages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3.0.2

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Build storybook
        run: |
          npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: src/storybook-static # The folder the action should deploy.
     # Use the secrets in the tests
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}    
