name: Main changed - build, then release and update GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: 16.19.0

  update-storybook-on-ghpages:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3.0.2

      - uses: ./.github/actions/cache-restore
        id: cache-node-modules
        with:
          node-version: 16.19.0

      - name: Show environment variables
        run: |
          echo "NEXTAUTH_SECRET: FDezLOOo4q+DeG3y0REbc8xOlFvciDD4pRIvCRaBQ1k="
          echo "NEXTAUTH_URL: http://localhost:3000"
          echo "KEYCLOAK_CLIENT_ID: "
          echo "KEYCLOAK_CLIENT_SECRET: "

      - name: Build storybook
        run: |
          npm run build-storybook -- --quiet --loglevel silent

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: src/storybook-static
